
"""
This module contains the utils for generating synthetic figures.

Axes labels and lists of colors, shapes, and filler materials.
"""

colors = [
    "blue",
    "green",
    "red",
    "cyan",
    "magenta",
    "black",
    "gold",
    "navy",
    "purple",
    "orange",
]

shapes = [
    "o",
    "s",
    "o",
    "s",
    "o",
    "D",
    "^",
    "v",
    "<",
    ">",
    "p",
    "*",
    "h",
    "H",
    "+",
    "x",
    "d",
]

positions = [
    "upper right",
    "upper left",
    "lower left",
    "lower right",
    "right",
    "center left",
    "center right",
    "lower center",
    "upper center",
    "center",
]

filler_axis_labels = [
    "Particle Density",
    "Temperature (°C)",
    "Electric Field (V/m)",
    "EV (V)",
    "Particle Size (nm)",
    "Aspect Ratio",
    "Shear Rate (1/s)",
    "Frequency (Hz)",
    "Strain",
    "Stress (Pa)",
    "Thickness (µm)",
    "Film Thickness (µm)",
    "Time (s)",
    "Curing Time (min)",
    "Aging Time (h)",
    "Annealing Temperature (°C)",
    "Pressure (Pa)",
    "pH",
    "Solvent Concentration (M)",
    "Surfactant Concentration (M)",
    "Particle Diameter (nm)",
    "Polymer Molecular Weight (g/mol)",
    "Curing Temperature (°C)",
    "Synthesis Temperature (°C)",
    "Synthesis Time (min)",
    "Stirring Speed (rpm)",
    "Mixing Time (min)",
    "Dispersing Time (min)",
    "Ultrasound Power (W)",
    "Ultrasound Time (min)",
    "Rotational Speed (rpm)",
    "Holding Time (min)",
    "Evaporation Temperature (°C)",
    "Drying Temperature (°C)",
    "Drying Time (h)",
    "Calcination Temperature (°C)",
    "Calcination Time (h)",
    "Heat Treatment Temperature (°C)",
    "Heat Treatment Time (h)",
    "Crosslinking Density (mol/m³)",
    "Reaction Temperature (°C)",
    "Reaction Time (h)",
    "Incubation Temperature (°C)",
    "Incubation Time (h)",
    "Aging Temperature (°C)",
    "Storage Time (days)",
    "Exposure Time (h)",
    "Light Intensity (W/m²)",
    "UV Exposure Time (h)",
    "Gamma Radiation Dose (Gy)",
    "X-ray Dose (Gy)",
    "Neutron Flux (n/cm²/s)",
    "Electron Beam Dose (Gy)",
    "Ion Beam Dose (Gy)",
    "Magnetic Field Strength (T)",
    "Dielectric Constant",
    "Dielectric Loss",
    "Specific Surface Area (m²/g)",
    "Pore Size (nm)",
    "Pore Volume (cm³/g)",
    "Crystallinity (%)",
    "Crystallization Temperature (°C)",
    "Melting Temperature (°C)",
    "Glass Transition Temperature (°C)",
    "Softening Temperature (°C)",
    "Degradation Temperature (°C)",
    "Decomposition Temperature (°C)",
    "Thermal Conductivity (W/(m·K))",
    "Thermal Diffusivity (mm²/s)",
    "Coefficient Of Thermal Expansion (1/K)",
    "Specific Heat Capacity (J/(g·K))",
    "Heat Capacity (J/K)",
    "Mechanical Strength (MPa)",
    "Young’s Modulus (GPa)",
    "Tensile Strength (MPa)",
    "Elongation At Break (%)",
    "Hardness (HV)",
    "Loading Concentration (%)",
    "Filler Content (%)",
    "vol%",
    "wt%",
    "Volume Fraction (%)",
    "Nanoparticle Volume (%)",
    "Nanoparticle Mass (%)",
    "filler labels",
    "Loading Concentration (%)",
    "Filler Content (%)",
    "vol% ",
    "wt%",
    "Volume Fraction (%)",
    "Volume Fraction",
    "Nanoparticle Volume (%)",
    "Nanoparticle Mass (%)",
]

filler_list = [
    "MMT",
    "high abrasion furnace black",
    "SiO2",
    "montmorillonite K-10",
    "Titanate nanotubes",
    "Lamp black",
    "multi-walled CNT",
    "multi-walled CNTs",
    "Silver",
    "Fullerene",
    "SWCNTs",
    "single-walled CNTs",
    "GO",
    "ZrO2",
    "Triphenyl phosphate",
    "Reduced graphene oxide",
    "expanded graphite",
    "carbon nanofibers",
    "Al2O3",
    "graphitic nanoplatelets",
    "CaCu3Ti4O12",
    "9-Anthracenemethanol",
    "Graphene oxide",
    "Fe3O4",
    "expandable graphite",
    "Graphene",
    "silica gel",
    "Single-wall carbon nanotubes",
    "Paraffinum liquidum",
    "Polyaniline",
    "Ba0.7Sr0.3TiO3",
    "OMMT",
    "Iron (II,III) Oxide",
    "Na2TiO3",
    "Aluminium",
    "Bentonite",
    "MWNT",
    "HAF",
    "TiO2",
    "Montmorillonite",
    "exfoliated graphite",
    "silica nanoparticles",
    "Silver nitrate",
    "Dodecylbenzenesulfonic acid",
    "BaTiO3",
    "Titanium Dioxide",
    "CCTO ceramics",
    "Zirconium dioxide",
    "Cellulose",
    "Molybdenum disulfide",
    "octyldimethylmethoxysilane",
    "carbon black",
    "White spirits",
    "Silica",
    "Titanium dioxide",
    "single-walled CNT",
    "9-anthracenemethanol",
    "MoS2",
    "alumina",
    "graphite",
    "graphene nanoribbon",
    "MgO",
    "barium titanate",
    "Channel black",
    "MWCNTs",
    "Au",
    "montmorillonite",
    "nanosilica",
    "Acetylene black",
    " Graphite",
    "Furnace black",
    "graphene nanoplatelets",
    "Carbon black",
    "Lead(II) sulfide",
    "Poly(vinyl alcohol)",
    "Calcium carbonate",
    "Talcum",
    "aluminum",
    "silver",
    "ZnO",
    "OAP-POSS",
    "Aluminium dioxide",
    "graphite nanoplatelets",
    "Graphite oxide",
    "sodium montmorillonite",
    "CaCO3",
    "FeO",
    "PAN",
    "cellulose nanowhiskers",
    "Barium strontium titanate",
    "Silicon carbide",
    "Iron(II,III) oxide",
    "Magnesium oxide",
    "SWCNT",
    "Copper(II) phenyl phosphate",
    "SWNT",
    "SAF",
    "Molybdenum Disulfide",
    "Calcium Carbonate",
    "graphite nanoplates",
    "silver hexafluoroantimonate",
    "Barium Titanate",
    "Gold",
    "CCTO",
    "Fe2O3",
    "SWNTs",
    "titania",
    "multi-walled carbon nanotube",
    "cellulose nanocrystals",
    "calcium copper titanate",
    "zinc oxide",
    "TPP",
    "rGO",
    "Molybdenum Disulphide",
    "Alumina",
    "OMLS",
    "C.I. Pigment Black 6",
    "clay",
    "graphite (as received)",
    "CuPP",
    "graphene platelet",
    "Morrocan montmorillonite",
    "Thermal black",
    "graphene",
    "Zinc oxide",
    "Silver hexafluoroantimonate",
    "Sepiolite",
    "Buckminsterfullerene",
    "zirconium dioxide",
    "graphene platelets",
    "Aluminium oxide",
    "Cu(HO3PC6H5)2",
    "Calcium copper titanate",
    "Cloisite",
    "Ag",
    "MWCNT",
    "TiNT",
    "Fluorine mica",
    "magnesium oxide",
    "Organophilic clay",
    "graphite oxide",
    "SiC powder",
    "OAPS",
    "Paraffin oil",
    "silica",
    "Clay",
    "Zinc Oxide",
    "fumed silica",
    "White mineral oil",
    "Graphite",
    "C60",
    "Multi-wall carbon nanotubes",
    "multi-wall carbon nanotubes",
    "polyaniline",
    "PbS",
    "Synthetic fluorine mica",
    "talc",
    "exfoliated graphene",
    "Graphite Nanoplatelets",
    "MWNTs",
    "Carbon Black",
    "Sodium titanate nanotubes",
    "barium strontium titanate",
    "dodecylbenzene sulfonic acid",
    "AuNPs",
    "OFG",
    "Methoxy(dimethyl)octylsilane",
    "Colloidal silica",
    "carbon nanotube",
    "Copper phenylphosphate",
    "graphene oxide",
    "Bentonite clay",
    "TiNTs",
    "Carbon nanofibers",
    "Mineral oil",
    "Silicon dioxide",
    "Barium titanate",
    "titanium dioxide",
    "PVA",
    "silicon dioxide",
    "Poly(acrylonitrile)",
    "cellulose nanocrystal",
    "calcium carbonate",
]

matrix_list = [
    "PDMS",
    "silicone",
    "P2VP",
    "CAB",
    "Poly(propylene)",
    "PVB",
    "EVA",
    "PEVA",
    "PEKK",
    "PA 6(3)T",
    "PA63T",
    "Nylon 8",
    "Polybenzimidazole",
    "Polyimide",
    "Poly(caprolactone)",
    "Poly(benzoxazine)",
    "Nylon 6T",
    "Poly(ethyl acrylate)",
    "Poly(vinyl chloride)",
    "PAM",
    "TGPAP",
    "poly-HEMA",
    "DGEBF Epoxy Resin",
    "Polybutylene succinate",
    "Poly(butylene)",
    "PTFE",
    "P(BA-a)",
    "Poly(BA-a)",
    "BXZ",
    "PBA-a",
    "Polychlorotrifluoroethylene",
    "Poly(acrylic acid)",
    "PAMS",
    "PαMS",
    "PMS",
    "Polybutadiene",
    "Polyurethane",
    "PAN",
    "PAA",
    "PANa",
    "P4VP",
    "Polyrotaxane",
    "PA 6",
    "Nylon 6",
    "PET",
    "PETE",
    "PETP",
    "PVP",
    "Nylon 11",
    "PU",
    "Nylon 6-6",
    "PA 8",
    "PEA",
    "Unsaturated polyester resin",
    "PEEK",
    "TGDDM",
    "VER",
    "Nylon 12",
    "PB-1",
    "BR",
    "PB",
    "PBD",
    "PCL",
    "PBT",
    "PBTP",
    "Sodium polyacrylate",
    "Cellulose acetate butyrate",
    "Poly(vinyl butyral)",
    "PHEA",
    "Poly(ethyl methacrylate)",
    "PBS",
    "BECy",
    "Silicone rubber",
    "Poly(acrylonitrile)",
    "PA 6T",
    "S-SEBS",
    "S-EB-S",
    "Polyetherketoneketone",
    "DGEBA Epoxy Resin",
    "Poly(ethylene-vinyl acetate)",
    "Polylactic acid",
    "PMMA-PnBA",
    "PTrFE",
    "Cyclic olefin copolymer",
    "Poly(ethylene glycol)",
    "DGEBD Epoxy Resin",
    "Poly(vinylidene fluoride)",
    "PA 66",
    "Nylon 66",
    "P(VDF-HFP)",
    "P(VDF-TrFE)",
    "Poly(4-vinyl pyridine)",
    "PBI",
    "PA 11",
    "Nylon 11",
    "PP",
    "iPP",
    "sPP",
    "aPP",
    "IMPP",
    "PEG",
    "PEO",
    "Poly(2-hydroxyethyl methacrylate)",
    "Nylon 6",
    "Poly(vinyl alcohol)",
    "Acrylonitrile butadiene styrene",
    "PVAc",
    "PVA",
    "PVAC",
    "PA 12",
    "Nylon 12",
    "PMMA-PtBA",
    "Thermoplastic polyurethane",
    "Poly(styrene-co-acrylonitrile)",
    "PGMA",
    "PBuA",
    "PBA",
    "PnBA",
    "PCTFE",
    "PTFCE",
    "PMMA-PnBA-PMMA",
    "Poly(methyl methacrylate)",
    "XNBR",
    "CNBR",
    "Poly(2-hydroxyethyl acrylate)",
    "PS",
    "PPSF",
    "PPSU",
    "Polyphenylsulfone",
    "TPU",
    "SAN",
    "SAN24",
    "Poly(methyl acrylate)",
    "Polyamide-imide",
    "NVE",
    "DGEBF",
    "EPDM",
    "EPDM rubber",
    "Poly(butylene terephthalate)",
    "Poly(ether ether ketone)",
    "ABS",
    "P(VDF-TrFE-CTFE)",
    "PRX",
    "PR",
    "PVC",
    "PVC-P",
    "PHFP",
    "COC",
    "Poly(glycidyl methacrylate)",
    "PC",
    "P(VDF-CTFE)",
    "Poly(vinyl acetate)",
    "Nylon 6(3)T",
    "P(Baph)",
    "BPA-Ph",
    "Poly(bisphenol A carbonate)",
    "PVOH",
    "PVA",
    "PVAL",
    "bisphenol-A phthalonitrile resin",
    "triglycidyl para-aminophenol",
    "Epoxy novolac viny ester resin",
    "PMA",
    "Poly(acrylamide)",
    "Poly(alpha-methylstyrene)",
    "Poly(butyl acrylate)",
    "FKM",
    "Poly(ethylene)",
    "PLA",
    "UPR",
    "Poly(hexafluoro propylene)",
    "Poly(vinyl pyrrolidone)",
    "PMMA",
    "PBAT",
    "PVDF",
    "Poly-trifluoroethylene",
    "Poly(styrene-b-butadiene)",
    "PAI",
    "SBR",
    "S-SBR",
    "E-SBR",
    "PS-I",
    "Poly(2-vinyl pyridine)",
    "Poly(tetrafluoroethylene)",
    "Poly(ethylene terephthalate)",
    "Fluoroelastomer",
    "Bisphenol E cyanate ester resin",
    "DGEBD",
    "Polystyrene",
    "PEMA",
    "PUR",
]

x_axis_labels = [
    "Particle Density",
    "Temperature (°C)",
    "Electric Field (V/m)",
    "EV (V)",
    "Particle Size (nm)",
    "Aspect Ratio",
    "Shear Rate (1/s)",
    "Frequency (Hz)",
    "Strain",
    "Stress (Pa)",
    "Thickness (µm)",
    "Film Thickness (µm)",
    "Time (s)",
    "Curing Time (min)",
    "Aging Time (h)",
    "Annealing Temperature (°C)",
    "Pressure (Pa)",
    "pH",
    "Solvent Concentration (M)",
    "Surfactant Concentration (M)",
    "Particle Diameter (nm)",
    "Polymer Molecular Weight (g/mol)",
    "Curing Temperature (°C)",
    "Synthesis Temperature (°C)",
    "Synthesis Time (min)",
    "Stirring Speed (rpm)",
    "Mixing Time (min)",
    "Dispersing Time (min)",
    "Ultrasound Power (W)",
    "Ultrasound Time (min)",
    "Rotational Speed (rpm)",
    "Holding Time (min)",
    "Evaporation Temperature (°C)",
    "Drying Temperature (°C)",
    "Drying Time (h)",
    "Calcination Temperature (°C)",
    "Calcination Time (h)",
    "Heat Treatment Temperature (°C)",
    "Heat Treatment Time (h)",
    "Crosslinking Density (mol/m³)",
    "Reaction Temperature (°C)",
    "Reaction Time (h)",
    "Incubation Temperature (°C)",
    "Incubation Time (h)",
    "Aging Temperature (°C)",
    "Storage Time (days)",
    "Exposure Time (h)",
    "Light Intensity (W/m²)",
    "UV Exposure Time (h)",
    "Gamma Radiation Dose (Gy)",
    "X-ray Dose (Gy)",
    "Neutron Flux (n/cm²/s)",
    "Electron Beam Dose (Gy)",
    "Ion Beam Dose (Gy)",
    "Magnetic Field Strength (T)",
    "Dielectric Constant",
    "Dielectric Loss",
    "Specific Surface Area (m²/g)",
    "Pore Size (nm)",
    "Pore Volume (cm³/g)",
    "Crystallinity (%)",
    "Crystallization Temperature (°C)",
    "Melting Temperature (°C)",
    "Glass Transition Temperature (°C)",
    "Softening Temperature (°C)",
    "Degradation Temperature (°C)",
    "Decomposition Temperature (°C)",
    "Thermal Conductivity (W/(m·K))",
    "Thermal Diffusivity (mm²/s)",
    "Coefficient Of Thermal Expansion (1/K)",
    "Specific Heat Capacity (J/(g·K))",
    "Heat Capacity (J/K)",
    "Mechanical Strength (MPa)",
    "Young’s Modulus (GPa)",
    "Tensile Strength (MPa)",
    "Elongation At Break (%)",
    "Hardness (HV)",
]

y_axis_labels = [
    "Tg (°C)",
    "Glass Transition Temperature (°C)",
    "Loss Modulus (Pa)",
    "Dielectric Loss",
    "Complex Modulus (Pa)",
    "Tan Delta",
    "Permittivity",
    "Loss Factor",
    "Thermal Conductivity (W/(m·K))",
    "Thermal Diffusivity (mm²/s)",
    "Coefficient Of Thermal Expansion (1/K)",
    "Heat Capacity (J/K)",
    "Specific Heat (J/(g·K))",
    "Thermal Stability (°C)",
    "Degradation Temperature (°C)",
    "Decomposition Temperature (°C)",
    "Crystallinity (%)",
    "Melting Temperature (°C)",
    "Heat Of Fusion (J/g)",
    "Heat Of Crystallization (J/g)",
    "Crystallization Temperature (°C)",
    "X-ray Diffraction Intensity",
    "Particle Size (nm)",
    "Particle Size Distribution",
    "Zeta Potential (mV)",
    "Surface Area (m²/g)",
    "Pore Size (nm)",
    "Pore Volume (cm³/g)",
    "Bet Surface Area",
    "Porosity (%)",
    "Hardness (HV)",
    "Elastic Modulus (GPa)",
    "Young’s Modulus (GPa)",
    "Tensile Strength (MPa)",
    "Elongation At Break (%)",
    "Toughness (MJ/m³)",
    "Fracture Toughness (MPa·m^0.5)",
    "Impact Strength (kJ/m²)",
    "Fatigue Strength (MPa)",
    "Flexural Strength (MPa)",
    "Shear Strength (MPa)",
    "Compression Strength (MPa)",
    "Bond Strength (MPa)",
    "Adhesion Strength (MPa)",
    "Peel Strength (N/m)",
    "Tensile Modulus (GPa)",
    "Flexural Modulus (GPa)",
    "Shear Modulus (GPa)",
    "Compressive Modulus (GPa)",
    "Bulk Modulus (GPa)",
    "Modulus Of Elasticity (GPa)",
    "Poisson’s Ratio",
    "Viscosity (Pa·s)",
    "Shear Viscosity (Pa·s)",
    "Complex Viscosity (Pa·s)",
    "Zero-shear Viscosity (Pa·s)",
    "Intrinsic Viscosity (dl/g)",
    "Dynamic Viscosity (Pa·s)",
    "Specific Viscosity",
    "Kinematic Viscosity (mm²/s)",
    "Dielectric Breakdown Strength (MV/m)",
    "Electric Field Strength (V/m)",
    "Conductivity (S/m)",
    "Electrical Conductivity (S/m)",
    "Ionic Conductivity (S/m)",
    "Electronic Conductivity (S/m)",
    "Thermal Conductivity (W/(m·K))",
    "Thermal Resistance (K/W)",
    "Thermal Expansion (1/K)",
    "Electrical Resistivity (Ω·m)",
    "Magnetic Susceptibility",
    "Saturation Magnetization (A/m)",
    "Coercivity (A/m)",
    "Remanence (A/m)",
    "Magnetic Permeability (H/m)",
    "Hysteresis Loss (J/m³)",
    "Magnetic Anisotropy (J/m³)",
    "Magnetoresistance",
    "Magnetization (A/m)",
    "Electrochemical Potential (V)",
    "Oxidation Potential (V)",
    "Reduction Potential (V)",
    "Galvanic Potential (V)",
    "Corrosion Rate (mm/year)",
    "Passivation Current Density (A/m²)",
    "Polarization Resistance (Ω·m²)",
    "Charge Transfer Resistance (Ω·m²)",
]
